chat/urls.py
import imp
from django.urls import path

from chat import views

app_name="chat"

urlpatterns = [
    path("chat/index/",views.Index.as_view(),name="index"),
    path("chat/<str:room_name>/",views.Room.as_view(),name="room"),
    path("chat/is_read/<str:room_name>/",views.MessageReadSet.as_view(),name="message"),
    path("chat/is_read/<str:room_name>/sendPhoto/",views.Send_Image,name="send_image"),
    path("chat/<str:room_name>/delete/",views.Delete_Message,name="delete_message"),
 
    
]

feed/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "feed"

urlpatterns = [
   
    # path("",views.HomePage.as_view(),name="home"),
    path("",views.HomePage.as_view(),name="home"),
    path("<int:pk>/",views.PostDetailView.as_view(),name="detail"),
    path("find/",views.FindFriends.as_view(),name="find"),
    path("uploadPost/",views.UploadPost.as_view(),name="new_post"),
    path("like/",views.Like_post ,name="like_post"),
    path("delete/",views.delete_post,name="delete"),
    path("update/",views.updatePost,name="update"),
    path("search/",views.FindFriends.as_view(),name="search"),
    path("comment/",views.Comment_post,name="comment"),
    path("favorites/",views.AddFavorites,name="add_to_favorites"),
    path('search_rooms/',views.Search_Room,name="search_room"),
    path("notification/<int:notification_pk>/post/<int:post_pk>",views.post_notification,name="post_notification"),
    path("notification/<int:notification_pk>/user_profile/<str:user_pk>",views.user_profile_notification,name="user_profile_notification"),
    path("delete_comment/",views.delete_comment,name="delete_comment"),
    path("update_comment/",views.update_comment,name="update_comment"),
    path("add_story/",views.addStory,name="add_story"),
    path("view_story/",views.View_story,name="view_story"),
    path("story_seen_add/",views.Story_Seen_Add,name="story_seen_add"),
    path("story_seen/",views.Story_Seen,name="story_seen_eye"),
    path("chat/",views.ChatView,name="template"),
    path("notification_clear/",views.Notification_Clear,name="notification_clear"),


   
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path 
from . import views

app_name = "profiles"

urlpatterns = [
 
    
    path("profile/<str:user_id>", views.ProfilePersonalUpdate.as_view(), name="update"),

    path("profile/<str:id>", views.ProfileLoginUpdate.as_view(), name="updatelogin"),
   
    path("<str:username>/", views.ProfileDetailView.as_view(), name="user_profile"),

    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),

    path("til/templates/",views.PasswordsChangeView.as_view(),name="reset"),

    path('til/templates/account/',views.password_success,name="password_success"),

    path('inbox/chat/',views.ListThreads.as_view(),name="inbox"),

    path('inbox/create_thread/',views.CreateThread.as_view(),name="create_thread"),

    path('inbox/<int:pk>/',views.ThreadView.as_view(),name="thread"),

    path('inbox/<int:pk>/<int:message_pk>',views.ReadMessage.as_view(),name="read_message"),

    path('inbox/<int:pk>/create_message/',views.CreateMessage.as_view(),name="create_message"),

    path("<str:username>/welcome/",views.welcome_email,name="welcome"),
    
]

til/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls, views
from chat import urls as chat_urls



urlpatterns = [
    path('admin/',include('admin_honeypot.urls', namespace="admin_honeypot")),
    path('socialbooksecurelogin/', admin.site.urls),
    path("",include(feed_urls, namespace="feed")),
    path("",include(profiles_urls, namespace="profiles")),
    url("",include("allauth.urls")),
    path('accounts/', include('allauth.urls')),
    path("",include(chat_urls,namespace="chat")),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

chat/models.py
from asyncio.windows_events import NULL
from sqlite3 import Timestamp
from turtle import ondrag
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Chat(models.Model):
    count = 0

    content = models.CharField(max_length=1555,null=True)
    photo = models.ImageField(upload_to="uploads/message_photos", blank = True, null = True)
    timestamp = models.DateTimeField(auto_now=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")
    room = models.ForeignKey('RoomChat',on_delete=models.CASCADE)
    is_read = models.BooleanField(default=False)

    def Counter(self):
        self.count += 1
        return self.count
    

# class Chatroom(models.Model):
#     sender = models.CharField(max_length=55)
#     receiver = models.CharField(max_length=55)
    
class RoomChat(models.Model):
    receiver = models.CharField(max_length=1055)
    sender = models.CharField(max_length=1055)
    sender_profile = models.ForeignKey(User,on_delete=models.CASCADE, related_name="+")
    receiver_profile = models.ForeignKey(User,on_delete=models.CASCADE, related_name="+")
    

class Connected(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="connected")
    room = models.ForeignKey(RoomChat, on_delete=models.CASCADE, related_name="connected")
    channel_name = models.CharField(max_length=100, null=False)
    connect_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

feed/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import IntegerField
from profiles.models import  Profile
from django.db.models.deletion import CASCADE
from sorl.thumbnail import ImageField
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class Post(models.Model):
    text = models.CharField(max_length=255)
    date_time = models.DateTimeField(auto_now=True)
    photo = ImageField(upload_to="uploads/posts")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,

    )
    likes = models.ManyToManyField(User, related_name="likes")
    


    def __str__(self):
        return self.text[0:100]

    @property
    def total_like(self):
        return self.likes.all().count()


STATUS =  (
        ('Like','Like'),
        ('Dislike','Dislike'),
    )


     
    
class Like(models.Model):
    user = models.ForeignKey(User,on_delete=CASCADE)
    post = models.ForeignKey(Post,on_delete=CASCADE)
    value = models.CharField(choices=STATUS,default='Like',max_length=9)
    
    def __str__(self):
       return str(self.post) 

class Stories(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=55,blank=True)
    created_time = models.DateTimeField(auto_now=True)
    photo = ImageField(upload_to="uploads/stories")
    viewers = models.ManyToManyField(Profile, related_name="viewers")
   
    # def __str__(self):
    #     return str(self.author.username + ' ') + str('- ' + self.text)

# class Stories_Seen(models.Model):
#     story = models.ForeignKey(Stories,on_delete=models.CASCADE)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)

 
class Comment(models.Model):
    
    user = models.ForeignKey(Profile,on_delete=CASCADE)
    post = models.ForeignKey(Post,on_delete=CASCADE)
    content = models.TextField(max_length=255)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.content)
        
class Favorites(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def  __str__(self):
        return self.user.username


class Notification(models.Model):

    notification_type = models.IntegerField()
    to_user = models.ForeignKey(User, related_name="notification_to", on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(User, related_name="notification_from" ,on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, related_name="+", on_delete=models.CASCADE,null=True, blank=True)
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    date = models.DateTimeField(auto_now_add=True)
    user_has_seen = models.BooleanField(default=False)

chat/views.py
from pickle import FALSE
import profile
import re
from django.dispatch import receiver
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from profiles.models import Profile
from django.views import View

from chat.models import Chat, RoomChat
# Create your views here.
def index(request):
    return render(request, 'chat/index.html')
class Index(LoginRequiredMixin, View):
    def get(self, request):
        rooms = RoomChat.objects.filter(Q(sender = request.user.username) | Q(receiver = request.user.username))
        chats = []
        for room in rooms:
            chat = Chat.objects.filter(room = room).last()
            chats.append(chat)
            
        for i in chats:
            print(i.content)
        # rooms = RoomChat.objects.all()
        # chats = Chat.objects.filter(Q(sender = request.user) | Q(receiver = request.user)).order_by['-timestamp']
  
        context = {
            'rooms' : rooms,
            'chats' :chats,
        }
        return render(request, 'chat/chatlist.html',context)

    

class Room(LoginRequiredMixin, View):
    def get(self, request, room_name):
        print("room name:",room_name)

        receiver = room_name
        room_profile = []
        try:
            received_user = User.objects.get(username=room_name)
        except Profile.DoesNotExist:
            received_user = None

        chats = []
       
           
        if RoomChat.objects.filter(sender = request.user.username, receiver = receiver):
                room = RoomChat.objects.filter(sender=request.user.username,receiver=receiver).first()
                chats = Chat.objects.filter(room=room).order_by("timestamp")
                room_name = room.id
                # unread_message = Chat.objects.filter(room=room).last()
                unread_message = Chat.objects.filter(room=room,is_read=False)
                
                for message in unread_message:
                    if message.sender.username != request.user.username:
                        print("chat message 1:",message.content)
                        message.is_read = True
                        message.save()

                
                print("im hereeee")
               
                # return redirect('profiles:thread', pk = threads.pk)
               
        elif RoomChat.objects.filter(sender = receiver,receiver = request.user):
                room = RoomChat.objects.filter(sender = receiver,receiver = request.user.username).first()
                chats = Chat.objects.filter(room=room).order_by("timestamp")
                room_name = room.id
                room_profile = RoomChat.objects.get(id=room.id)
                unread_message = Chat.objects.filter(room=room,is_read=False)
                

                for message in unread_message:
                    if message.sender.username != request.user.username:
                        print("chat message 2:",message.content)
                        message.is_read = True
                        message.save()
                print("im hereeaa")
                # return redirect('profiles:thread', pk = threads.pk)
                # return render(request, 'chat/room.html', {'room_name': room_name, 'chats':chats, 'room':room})
          

        else:
                room = RoomChat(sender=request.user.username,receiver=receiver,sender_profile=request.user, receiver_profile = received_user)
                room.save()
                chat = Chat(sender=request.user, receiver=received_user, room=room)
                chat.save()
                # return render(request, 'chat/room.html', {'room_name': room_name, 'chats':chats, 'room':room})
       
        
        return render(request, 'chat/room.html', {'room_name': room_name, 'chats':chats, 'room':room, 'received_user':received_user})
   

class MessageReadSet(LoginRequiredMixin,View):
    def get(self, request, room_name):
        print("room_name:",room_name)
        receiver = room_name
        if RoomChat.objects.filter(sender = request.user.username, receiver = receiver):
                room = RoomChat.objects.filter(sender=request.user.username,receiver=receiver).first()
                print("room id:",room.id)
                chats = Chat.objects.filter(room=room).last()
                print("chat sender:",chats.sender.username)
                print("request user:",request.user.username)
                if chats.sender.username != request.user.username:
                
                    print("chat message 1:",chats.content)
                    chats.is_read = True
                    chats.save()
                # chats.is_read = True
                # chats.save()
                # room_name = room.id
                
                print("im hereeee")
               
                # return redirect('profiles:thread', pk = threads.pk)
               
        elif RoomChat.objects.filter(sender = receiver,receiver = request.user):
                room = RoomChat.objects.filter(sender = receiver,receiver = request.user.username).first()
                print("room id:",room.id)
                chats = Chat.objects.filter(room=room).last()
                if chats.sender.username != request.user.username:

                    print("chat message 2:",chats.content)
                    chats.is_read = True
                    chats.save()
                # chats.is_read = True
                # chats.save()
                # room_name = room.id
                # chats.is_read = True
                # chats.save()
                # room_profile = RoomChat.objects.get(id=room.id)
                print("im hereeaa")

        return redirect('chat:room',room_name)


def Send_Image(request,room_name):
    if request.method =='POST':
        text_message = request.POST.get("text")
        photo = request.FILES.get("photo")
        sender = User.objects.get(id=request.POST.get("sender"))
        receiver = User.objects.get(username=request.POST.get("receiver"))
        room_id = RoomChat.objects.get(id=request.POST.get("room_id"))
        print("text:",text_message)
        print("photo:",photo)
        print("receiver:",receiver)
        print("sender:",sender)
        print("room:",room_id)
        chat = Chat.objects.create(
            content = text_message,
            sender = sender,
            receiver = receiver,
            photo = photo,
            room = room_id,
            is_read = False,
        )
        chat.save()
        return JsonResponse({"message":"success","current_sender":request.POST.get("sender"),"receiver":request.POST.get("receiver"),"sender_avatar":sender.profile.image.url})
    return JsonResponse({"message":"not"})


def Delete_Message(request,room_name):
    if request.method == 'POST':
        msg_id = request.POST['msg_id']
        print("msg_id:",msg_id)           
        chat = Chat.objects.get(id=msg_id)
        chat.delete()
        print("chat message:",chat.content)
        return JsonResponse({"message":"success","content":chat.content})
    return JsonResponse({"message":"not"})

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
Chat Room
{% endblock title %}
    
{% block body %}
    {{ room_name|json_script:"room-name" }}
    {{ room.id|json_script:"room_id" }}
    {{ received_user.username|json_script:"received_user" }}
    {{ request.user.username | json_script:"sender" }}
    {{ request.user.id | json_script:"sender_id" }}   
    
<!-- component -->


   

   
<div class="fixed top-0 left-0 right-0 z-40 ">
   {% include 'includes/navbar.html' %}
 </div>



<div class="h-screen bg-gray-300 my-4">
   <div class="flex justify-center items-center bg-white h-screen ">
       <div class="w-4/5 h-fit rounded shadow-2xl">
           <nav class="w-full h-10 bg-gray-300 shadow-lg  rounded-lg rounded-bl-none rounded-br-none flex justify-between items-center">
               <div class="flex justify-center items-center"> <i class="mdi mdi-arrow-left font-normal text-gray-300 ml-1"></i>
                   <!-- <img src="https://i.imgur.com/IAgGUYF.jpg" class="rounded-full ml-1" width="25" height="25">  -->
                   
                   {% thumbnail received_user.profile.image "100x100" crop="center" as img %}
                   <img id="user_dp" src="{{img.url}}" alt="user image"  class="w-8 h-8 rounded-full">
                   {% endthumbnail %}
                   <span class="text-xs md:text-sm font-medium text-gray-700 ml-1 ">{{received_user.username | capfirst }}</span> 
               </div>
               <div class="flex items-center">

                  
                  <button >
                     <i class='mdi mdi-video text-gray-300 hover:text-gray-700 ' ></i>
                  </button>
                  <button >
                     <i class='mdi mdi-dots-vertical text-gray-300 hover:text-gray-700 ' ></i>
                  </button>
               </div>
            
             
                       
           </nav>
   
           <div id="chat-log" class="overflow-auto px-1 py-1" style="height: 24rem;" id="journal-scroll">
               {{ received_user.profile.image.url|json_script:"user_avatar" }}
               <div id="chat_list">

                  
                  {% for chat in  chats %}
                        
                        {% if chat.content %}
                                 
                                 {% ifchanged chat.timestamp.date %}
                                 <div class="flex justify-center"> <span class="text-gray-500 text-xs" style="font-size: 8px;">{{ chat.timestamp | date:"d F y"}}</span> </div>                  
                                 {% endifchanged %}

                                 
                                 {% if chat.sender.id == request.user.id %}

                                 
                                    {% if chat.photo %}
                                          <div class="flex items-end justify-end">
                                             <img id="media_message{{chat.id}}" class="w-22 h-16 md:w-48 md:h-32 justify-end" src="{{chat.photo.url}}" alt="Photo Attachements">
                                          </div>
                                    {% endif %}
                                    <div class="message_btn chat-message mb-1" id="{{chat.id}}">
                                       <div class="flex justify-end pt-2 pl-10"> 
                                          <span id="message_btn{{chat.id}}" class="sender_msg bg-gradient-to-r from-indigo-700 via-indigo-600 to-indigo-800
                                                      h-auto text-white text-xs font-normal p-1 rounded-lg rounded-tr-none px-1 items-end flex justify-end "
                                                style="font-size: 12px;" >
                                             {{chat.content}}
                                             <span class="text-gray-400 pl-1" style="font-size: 8px;">     {% load tz %}
                                                {% timezone "Asia/Kolkata" %}
                                                   {{chat.timestamp | time:"h:i:A"}}
                                                {% endtimezone %}</span>
                                          </span> 
                                       </div>
                                    </div>
                                 
                                 {% else %}
                                       
                                       {% if chat.photo %}
                                          <div class="flex items-end">
                                             <img class="w-22 h-16 md:w-48 md:h-32 items-end" src="{{chat.photo.url}}" alt="Photo Attachements">
                                          </div>
                                       {% endif %}
                                       <div class="chat-message mb-1 my-1">

                                       </div>
                                       <div class="flex items-center pr-10 mt-1"> 
                                          <img src="{{received_user.profile.image.url}}" class="rounded-full shadow-xl" width="15" height="15"> 
                                          
                                          <span class="flex ml-1 h-auto 
                                          bg-gradient-to-r from-purple-900 via-violet-600 to-purple-900
                                          text-white text-xs p-1 font-normal px-1 items-end rounded-lg rounded-bl-none" 
                                             style="font-size: 12px;">
                                             {{chat.content}}
                                             <span class="text-gray-400 pl-1" style="font-size: 8px;">
                                                {% timezone "Asia/Kolkata" %}
                                                {{chat.timestamp | time:"h:i:A"}}
                                             {% endtimezone %}
                                             </span>
                                          </span> 
                                       </div>
                                    
                                 {% endif %}
                                    
                                                            
                        {% endif %}
                                                
                  {% endfor %}
                     
                  
                  
                  
      
                  <div class=" " id="chatmsg"> </div>
               </div>
           </div>
              <!-- Chat Buttons -->
           <div class="flex justify-center items-center p-1 bg-gray-300 shadow-lg rounded-bl-lg rounded-br-lg">
               <div class="relative">
                  <div class="relative"> 
                     <i class="mdi mdi-emoticon-excited-outline absolute top-1 left-1 text-white" style="font-size: 17px !important;font-weight: bold;"></i> 
                     <input  id="chat-message-input" type="text" class="rounded-full pl-6 pr-12 py-2 focus:outline-none h-auto placeholder-gray-100 bg-gray-400 text-white" style="font-size: 11px;width: 225px;" placeholder="Type a message..." id="typemsg"> 
                     <i id="id_image" class="mdi mdi-camera absolute right-2 top-1 text-white"></i>
                   </div>
                  
               
               </div>
              
               <div class="w-7 h-7 rounded-full  bg-gradient-to-r from-purple-900 via-violet-600 to-purple-900 text-center items-center flex justify-center"> 
                  <button id="chat-message-submit" class="w-7 h-7 rounded-full text-center items-center flex justify-center focus:outline-none hover:bg-gray-900 hover:text-white" >
                     <i class="mdi mdi-send  text-white"></i>
                  </button>
                  {{request.user.id|json_script:"user_id"}}
                  {{ room.id | json_script:"room_id" }}
               </div>
               <div id="trash_message" class="hidden w-7 h-7 rounded-full  bg-gradient-to-r from-purple-900 via-violet-600 to-purple-900 text-center items-center flex justify-center"
                    data-message-delete-url="{% url 'chat:delete_message' received_user.username %}"> 
                  <button  class="w-7 h-7 rounded-full text-center items-center flex justify-center focus:outline-none hover:bg-gray-900 hover:text-white" >
                     <i class='bx bx-trash text-gray-100 hover:text-gray-500' ></i>
                  </button>

               </div>
           </div>
       </div>
   </div>
   </div>

        <!-- TODO:Upload Post -->
        <div class="min-w-screen animated fadeIn faster  fixed  left-0 top-0 flex justify-center items-center inset-0 z-40 outline-none focus:outline-none bg-no-repeat bg-center bg-cover hidden js-sendphoto-model"  id="modal-id">
           <div class="absolute bg-black opacity-75 inset-0 z-0 w-100"></div>
           <div class="relative mx-auto my-auto rounded-xl shadow-lg backdrop-opacity-10 backdrop-invert bg-white/30 shadow-lg border backdrop-filter backdrop-blur-xl w-fit h-auto md:w-2/5 p-1 md:p-3 ">
           <!--content-->
             <div class=" m-auto">
             <!--body-->
             <!-- <i class='bx bx-upload text-5xl text-blue-500 text-center'></i> -->
                 <div class="text-center pt-1 md:pt-5  flex-auto justify-center ">
                 
                     <!-- TODO:Add the ajax form -->
   
                       <div class="md:flex-row pt-3 px-0 md:px-3     " style="text-align: -webkit-center;">
                         <div class=" flex flex-col md:flex-row w-3/5 items-baseline "><label  for="id_photo"  class="text-xs md:text-sm text-center text-white">Photo:</label> </div>
                         <input type="file" class="js-send-photo text-center flex flex-col md:flex-row text-xs md:text-sm w-3/5 items-baseline mb-2 text-white" name="photo" required id="id_attachment"></div>
                       <!-- <div id="img-box"  class="w-1/2 h-12 md:h-1/4 md:w-1/2 relative mx-auto"></div> -->
                       <img id="img-send-box"  alt="Upload Photo" class="w-22 h-16 md:w-48 md:h-32 border relative mx-auto ext-xs md:text-sm text-white"></img>
                     
                     <textarea class="js-message-text  text-xs md:text-sm border-2 border-blue-500 mt-2 md:mt-4 w-3/5 h-9 md:h-11"  rows="2" placeholder="Message Text" maxlength="255"  required id="id_text" data-message-url="{% url 'chat:send_image' received_user.username  %} " ></textarea>
                             
                       
                 </div>
             <!--footer-->
                 <div class="  text-center space-x-1 md:block  mt-4">
   
                 <button class="js-send_image  bg-blue-500 text-white font-semibold mb-2 md:mb-0 px-3 py-1 
                               md-py-2 border-b-2 border-green-500 shadow-sm font-medium tracking-wider border 
                               rounded-full hover:shadow-lg hover:bg-gray-100 mr-2 hover:border-green-600 hover:bg-green-500 hover:text-white
                               shadow-md inline-flex text-xs md:text-sm mr-2">
                               Send Message
                 
                 </button>
                 
                   <button class="js-toggle-photo-model-cancel text-xs md:text-sm mb-2 md:mb-0 px-3 py-1 md-py-2  bg-white text-sm shadow-sm font-medium tracking-wider border text-gray-600 rounded-full hover:shadow-lg  ">
                     Cancel
                   </button>
                 </div>
                 <div id="alert-box"></div>
               </div>
           </div>
         </div>



<script>
   
</script>












<!-- Endof Template -->

  
{% endblock body %}