chat/urls.py
import imp
from django.urls import path

from chat import views

app_name="chat"

urlpatterns = [
    path("chat/index/",views.Index.as_view(),name="index"),
    path("chat/<str:room_name>/",views.Room.as_view(),name="room"),
    path("chat/is_read/<str:room_name>/",views.MessageReadSet.as_view(),name="message"),
    path("chat/is_read/<str:room_name>/sendPhoto/",views.Send_Image,name="send_image"),
    path("chat/<str:room_name>/delete/",views.Delete_Message,name="delete_message"),
 
    
]

feed/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "feed"

urlpatterns = [
   
    # path("",views.HomePage.as_view(),name="home"),
    path("",views.HomePage.as_view(),name="home"),
    path("<int:pk>/",views.PostDetailView.as_view(),name="detail"),
    path("find/",views.FindFriends.as_view(),name="find"),
    path("uploadPost/",views.UploadPost.as_view(),name="new_post"),
    path("like/",views.Like_post ,name="like_post"),
    path("delete/",views.delete_post,name="delete"),
    path("update/",views.updatePost,name="update"),
    path("search/",views.FindFriends.as_view(),name="search"),
    path("comment/",views.Comment_post,name="comment"),
    path("favorites/",views.AddFavorites,name="add_to_favorites"),
    path('search_rooms/',views.Search_Room,name="search_room"),
    path("notification/<int:notification_pk>/post/<int:post_pk>",views.post_notification,name="post_notification"),
    path("notification/<int:notification_pk>/user_profile/<str:user_pk>",views.user_profile_notification,name="user_profile_notification"),
    path("delete_comment/",views.delete_comment,name="delete_comment"),
    path("update_comment/",views.update_comment,name="update_comment"),
    path("add_story/",views.addStory,name="add_story"),
    path("view_story/",views.View_story,name="view_story"),
    path("story_seen_add/",views.Story_Seen_Add,name="story_seen_add"),
    path("story_seen/",views.Story_Seen,name="story_seen_eye"),
    path("chat/",views.ChatView,name="template"),
    path("notification_clear/",views.Notification_Clear,name="notification_clear"),


   
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path 
from . import views

app_name = "profiles"

urlpatterns = [
 
    
    path("profile/<str:user_id>", views.ProfilePersonalUpdate.as_view(), name="update"),

    path("profile/<str:id>", views.ProfileLoginUpdate.as_view(), name="updatelogin"),
   
    path("<str:username>/", views.ProfileDetailView.as_view(), name="user_profile"),

    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),

    path("til/templates/",views.PasswordsChangeView.as_view(),name="reset"),

    path('til/templates/account/',views.password_success,name="password_success"),

    path('inbox/chat/',views.ListThreads.as_view(),name="inbox"),

    path('inbox/create_thread/',views.CreateThread.as_view(),name="create_thread"),

    path('inbox/<int:pk>/',views.ThreadView.as_view(),name="thread"),

    path('inbox/<int:pk>/<int:message_pk>',views.ReadMessage.as_view(),name="read_message"),

    path('inbox/<int:pk>/create_message/',views.CreateMessage.as_view(),name="create_message"),

    path("<str:username>/welcome/",views.welcome_email,name="welcome"),
    
]

til/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls, views
from chat import urls as chat_urls



urlpatterns = [
    path('admin/',include('admin_honeypot.urls', namespace="admin_honeypot")),
    path('socialbooksecurelogin/', admin.site.urls),
    path("",include(feed_urls, namespace="feed")),
    path("",include(profiles_urls, namespace="profiles")),
    url("",include("allauth.urls")),
    path('accounts/', include('allauth.urls')),
    path("",include(chat_urls,namespace="chat")),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

profiles/models.py
from base64 import urlsafe_b64encode
from xml.etree.ElementInclude import include
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.loader import render_to_string,get_template
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage,message
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from pathlib import Path
from chat.models import RoomChat, Chat
from sorl.thumbnail import ImageField


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = ImageField(default="user.png",upload_to='profiles')
    gender = models.CharField(null=True,blank=True,max_length=100)
    # dob = models.DateTimeField(auto_created=True)
    bio = models.TextField(null=True,blank=True,max_length=255)
    contact = models.IntegerField(null=True,blank=True,default=1)

    place = models.CharField(null=True,blank=True,max_length=100)
    state = models.CharField(null=True,blank=True,max_length=100)
    country = models.CharField(null=True,blank=True,max_length=100)
   

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django User is created."""
    if created:
        Profile.objects.create(user=instance)
        # current_site = get_current_site(instance)
        # mail_subject = 
        # html_content = '<p>This is an <strong>important</strong> message.</p>'
        # message = render_to_string('profiles/welcome_email.html',{
        #     'user':instance,
        #     'domain':current_site,
        #     'uid':urlsafe_base64_encode(force_bytes(instance.id)),
        #     'token':default_token_generator.make_token(instance),
        # })
        
        # send_email = EmailMessage(mail_subject,message,to=[to_email])
        
        # send_email.send()

        to_email = instance.email
        subject, from_email, to = 'Welcome to SocialBook Family', 'hellosocialbook@gmail.com', to_email
        text_content = 'Hi.'
        # html_content = render_to_string('profiles/welcome_user_email.html')
        context_data = {'name':instance.username}
        html = get_template('profiles/welcome_user_email.html')
        html_content = html.render(context_data)

        msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
        # msg.attach_alternative(html_content, "text/html")
        msg.content_subtype = 'html'
        msg.send(fail_silently=False)


        # Automatic Message From SocialBook To New user
        try:
            admin = User.objects.get(username='social')
            print("Admin Exists")
            room = RoomChat.objects.create(sender='social', receiver=instance.username, sender_profile = admin, receiver_profile = instance)
            room.save()
            chat = Chat.objects.create(
                content = "Welcome To SocialBook "+instance.username,
                sender = admin,
                receiver = instance,
                room = room,
            )
            chat.save()
            chat = Chat.objects.create(
                content = "Your story starts with us. We are so happy to have you here!, you are now part of a community that helps you to connect and share with the people in your life, Thank you for joining with us",
                sender = admin,
                receiver = instance,
                room = room,
            )
            chat.save()
        except User.DoesNotExist:
            pass

profiles/views.py
from django.contrib.auth.models import User
from django.forms import forms
from django.shortcuts import redirect, render
from django.contrib import messages
from django.db.models import Q
from django.views.generic import DetailView, View, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest, request
from django.views.generic.base import TemplateView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse_lazy
from feed.models import Favorites, Notification, Post
from followers.models import Follower
from profiles.forms import  UserForm
from profiles.models import Profile

class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    # success_url = reverse_lazy('password_success')
    success_url = reverse_lazy('profiles:password_success')
    template_name="account/password_change.html"

def password_success(request):
    messages.success(request,"Your Password has been Updated SuccessFully")
    return render(request,'account/password_success.html',{})


class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/my_profile_details.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        # U = User.objects.get(username=user)
        # U.set_password('appu123456789111')
        # U.save()
        user = User.objects.get(username = self.kwargs['username'])

        print("user:",self.kwargs['username'])
        email = user.email
        favorites = Favorites.objects.filter(user__username = self.kwargs['username'])
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        context['userss'] = User.objects.get(username = self.kwargs['username'])
        context['total_followers'] = Follower.objects.filter(following=user).count()
        context['total_following'] = Follower.objects.filter(followed_by = user).count()
        context['favorites'] = favorites
        context['profile_name'] = email.split('@')[0]
        context['posts'] = Post.objects.filter(author = user)
    
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        return context

class ProfilePersonalUpdate(UpdateView):
    template_name = "profiles/profile_update.html"
    model = Profile
    # form_class = UserForm
    fields = "__all__"
    success_url = "/"
    slug_field = "user_id"
    slug_url_kwarg = "user_id"
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request,*args,**kwargs)

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author = user).count()
        context['total_followers'] = Follower.objects.filter(following = user).count()
        context['total_following'] = Follower.objects.filter(followed_by = user).count()
        return context

    def form_valid(self, form):
        messages.success(self.request,'User Details Updated Successfully')
        return super().form_valid(form)


        


class ProfileLoginUpdate(UpdateView):
    template_name = "profiles/updateuser.html"
    model = User
    
    fields = "__all__"
    success_url = "/"
    slug_field = "id"
    slug_url_kwarg = "id"
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request,*args,**kwargs)

    def form_valid(self, form):
        messages.add_message(self.request ,messages.SUCCESS,'User Details Updated Successfully')
        return super().form_valid(form)

class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")

        if data['action'] == "follow":
            # Follow
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
            notification = Notification.objects.create(
                notification_type = 3,
                from_user = request.user,
                to_user = other_user,

            )
            notification.save()
        else:
            # Unfollow
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user,
                )
            except Follower.DoesNotExist:
                follower = None

            if follower:
                follower.delete()

        return JsonResponse({
            'success': True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })




class ListThreads(View):
    template_name = "profiles/detail.html"
    def get(self, request, *args, **kwargs):
        threads = ThreadModel.objects.filter(Q(user = request.user) | Q(receiver = request.user))
    
        message_list = MessageModel.objects.all()
       
        context = {
            'threads' : threads,
            'message_list' :message_list,
        }

        return render(request,'includes/chat/inbox.html',context)
    
def ListThread(request):

    return render(request,'includes/chat/inbox.html')

class CreateThread(View):
    def get(self, request, *args, **kwargs):
        form = ThreadForm()
        
        context = {
            'form' : form,   
        }

        return render(request,'includes/chat/create_thread.html',context)
    def post(self, request, *args, **kwargs):
        form = ThreadForm(request.POST)
        username = request.POST.get('username')

        try:
            receiver = User.objects.get(username = username)
            if ThreadModel.objects.filter(user = request.user, receiver = receiver):
                threads = ThreadModel.objects.filter(user = request.user, receiver = receiver)[0]
                return redirect('profiles:thread', pk = threads.pk)
            elif ThreadModel.objects.filter(user = receiver, receiver = request.user).exists():
                   threads = ThreadModel.objects.filter(user = receiver, receiver = request.user)[0]
                   return redirect('profiles:thread', pk = threads.pk)
            if form.is_valid():
                threads = ThreadModel(
                    user = request.user,
                    receiver = receiver
                )
                threads.save()
                return redirect('profiles:thread', pk = threads.pk)

        except:
            return redirect('profiles:create_message')

class ThreadView(View):
    def get(self, request, pk, *args, **kwargs):
        form = MessageForm()
        thread = ThreadModel.objects.get(pk = pk)
        message_list = MessageModel.objects.filter(thread__pk__contains = pk)
        context = {
            'form' : form,
            'thread' : thread,
            'message_list' : message_list,
        }
        return render(request,'includes/chat/thread.html',context)

class ReadMessage(View):
    def get(self, request, pk, message_pk, *args, **kwargs):
        form = MessageForm()
        thread = ThreadModel.objects.get(pk = pk)
        message_list = MessageModel.objects.filter(thread__pk__contains = pk)
        message = MessageModel.objects.get(pk = message_pk)
        print("message from readmessage",message.body)
        message.is_read = True
        message.save()
        context = {
            'form' : form,
            'thread' : thread,
            'message_list' : message_list,
        }
        return render(request,'includes/chat/thread.html',context)
class CreateMessage(View):
    def post(self, request, pk, *args, **kwargs):
        form = MessageForm(request.POST,request.FILES)
        thread = ThreadModel.objects.get(pk = pk)
        receiver_user = request.POST['receiver_user']
        receiver = User.objects.get(id=receiver_user)
    
        print("thread:",thread)
        if thread.receiver == request.user:
            receiver = thread.user
        else:
            receiver = thread.receiver

     
        message = form.save(commit=False)
          
        message.thread = thread
        message.sended_user = request.user
        message.receiver_user = receiver
        message.save()
      
        print(form.errors)

        notification = Notification.objects.create(
            notification_type = 4,
            to_user = receiver,
            from_user = request.user,
            thread = thread,
            message = message,
            
        )
        notification.save()
     
        # print("receiver:",receiver_id)
    
        # return render(request,'includes/chat/thread.html',context)
        return redirect('profiles:thread', pk = pk)



def welcome_email(request,username):
    return render(request,'profiles/welcome_user_email.html')

profiles/templates/profiles/profile_update.html
{% extends 'base.html' %}
{% load thumbnail %}
<!-- {% block title %}{{ user.username }}{% endblock title %} -->

{% block body %}

<title>{{ user.username }}</title>





{% if request.user.is_authenticated %}
<div class="fixed top-0 left-0 right-0 z-50 ">
  {% include 'includes/navbar.html' %}
</div>
<div class="flex  bg-gray-100 max-w-7xl mt-16 md:mt-28">
  
 
  <div class="overflow-hidden  w-full h-fit z-40 md:z-30 my-3 backdrop-blur-sm bg-white/30 " style="backdrop-filter: blur(20px);">
 
    <!-- <img src="https://images.unsplash.com/photo-1593642532454-e138e28a63f4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80" class="bg-cover" /> -->
    <div class=" flex justify-center mt-4">
      <a href="{{user.profile.image.url}}">
      {% thumbnail user.profile.image "100x100" crop="center" as im %}
    
      <img src="{{ im.url }}" alt="" class="rounded-full border-solid border-white border-2 -mt-3 grayscale ">
      {% endthumbnail %}
    </a>
 
</div>

      <div class="flex flex-col gap-1 text-center">
       
          <div class="flex font-serif font-semibold self-center">{{user.username | capfirst}}
                <!-- <button class="flex  rounded-full h-4 w-4 md:h-5 md:w-5 text-sm md:text-2xl
                text-white font-semibold border-2 flex justify-center items-center font-mono hover:bg-blue-700">
                <i class='bx bx-camera text-gray-500'></i>
                </button> -->
          </div>
          <span class="text-xs md:text-sm text-black font-semibold">{{user.profile.bio | capfirst}}</span>
          <span class="text-xs md:text-sm text-gray-400">
              
              {% if user.profile.country %}
                  {{user.profile.country}},
              {% else %}
                  Country,
              {% endif %}
              
              {% if user.profile.state %}
                  {{user.profile.state}},
              {% else %}
                  State,
              {% endif %}
                  
              {% if user.profile.place %}
                  {{user.profile.place}}
              {% else %}
                  City
              {% endif %}
                  
          </span>
          <span class="text-sm text-gray-400">{{user.email}}</span>
        
          {% else %}
          <div class="mt-3 text-sm">Login to Update this user</div>
          {% endif %}
      </div>

      <!-- TODO:POsts,Followers,Following Details -->
      <div class="flex justify-center items-center mt-3 text-sm md:text-base">
        <div class="font-semibold text-center mx-4 text-black">
            {{total_posts}}
            <div class="text-gray-400">Posts</div>
        </div>
        <div class="font-semibold text-center mx-4 text-black">
           {{total_followers}}
            <div class="text-gray-400">Followers</div>
        </div>
        <div class="font-semibold text-center mx-4 text-black">
           {{total_following}}
            <div class="text-gray-400">Folowing</div>
        </div>
    </div>


    <!-- TODO:About -->
    <div class="flex flex-col my-3 text-gray-700">
      <div class="flex justify-between items-center">
        <div class="text-sm md:text-lg pl-1 md:pl-3 font-bold ">Personal Detailsss</div>

      </div>
      <hr>
      <form class="w-full max-w-lg self-center" method="post" enctype="multipart/form-data">
          
        {% csrf_token %}
        <!-- {{form.as_p}} -->
      <div class="flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
            USER NAME
          </label>
          <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-2 px-4 mb-1 md:mb-3 leading-tight focus:outline-none focus:bg-white" type="text" name="username"
          value="{{user.username}}" maxlength="150" required id="id_username">
        </div>
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_email">
            Email
          </label>
          <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-2 px-4 mb-1 md:mb-3 leading-tight focus:outline-none focus:bg-white" id="email" type="text" placeholder="{{user.email}}">
        </div>
     
      </div>
      
     

      <!-- TODO:Personal Details -->
      <div class="my-3 text-gray-700">
            <p class="hidden"><label for="id_user">User:</label>
              <select name="user" required id="id_user">
                <option value="">---------</option>
                <option value="{{user.id}}" selected>{{user.profile.user}}</option>
              </select></p>
           
          <!-- New Form -->
            <div class="flex flex-wrap -mx-3 mb-6">
              <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_image">
                  Image
                </label>
                <a href="{{user.profile.image.url}}">
                  <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-2 px-4 mb-1 md:mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" placeholder="{{user.profile.image}}">
                </a>
                
              </div>
              <div class="w-full md:w-1/2 px-3 self-center">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_change_photo">
                  CHANGE PHOTO
                </label>
                <input class="form-control
                block
                w-full
                px-3
                py-1.5
                text-base
                font-normal
                text-gray-700
                bg-white bg-clip-padding
                border border-solid border-gray-300
                rounded
                transition
                ease-in-out
                m-0
                focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"  
                type="file" name="image" id="id_image">
              </div>
            </div>
          <!-- TODO:BIO -->
            <div class="flex flex-wrap -mx-3 mb-2">
              <div class="w-full px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_gender">
                  BIO
                </label>
                <textarea class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-2 md:py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"  name="bio" maxlength="100" required id="id_bio">{{user.profile.bio}}</textarea>
                <p class="text-gray-600 text-xs italic">Make it as long and as crazy as you'd like</p>
              </div>
            </div>
            <!--TODO:GENDER,CONTACT -->
            <div class="flex flex-wrap -mx-3 mb-6">
              <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_gender">
                  GENDER
                </label>
                <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-2 px-4 mb-1 md:mb-3 leading-tight focus:outline-none focus:bg-white" type="text"
                name="gender" value="{{user.profile.gender}}" maxlength="100" required id="id_gender">
              </div>
              <div class="w-full md:w-1/2 px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"for="id_contact">
                  CONTACT
                </label>
                <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-2 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" type="number"
                name="contact" value="{{user.profile.contact}}" required id="id_contact">
              </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-2">
              <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_place">
                  PLACE
                </label>
                <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-2 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" type="text"
                name="place" value="{{user.profile.place}}" maxlength="100" required id="id_place">
              </div>
              <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_state">
                  STATE
                </label>
                <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-2 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" type="text"
                name="state" value="{{user.profile.state}}" maxlength="100" required id="id_state">
              </div>
              <div class="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_country">
                  COUNTRY
                </label>
                <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-2 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" type="text"
                name="country" value="{{user.profile.country}}" maxlength="100" required id="id_country">
              </div>
            </div>
            <div class="flex flex-wrap -mx-1 md:-mx-3 my-2 md:my-6 justify-center">
              
              <div class="w-1/2 md:w-1/4 self-center text-center">
                <a class=" text-sm md:text-base  " href="{% url 'profiles:reset' %}">
                <button class="bg-white text-sm hover:bg-gray-100 text-gray-800 font-semibold w-auto p-2 border border-gray-400 rounded shadow">
                  Change Password
                </button>
                </a>
              </div>
              <div class="w-1/2 md:w-1/4 self-center text-center my-2">
              
                {% if request.user == user %}
          
                  <button
                    class="bg-blue-700 hover:bg-blue-300 text-white text-sm font-semibold w-auto p-2 focus:outline-none focus:shadow-outline rounded align-center"
                    type="submit">Update Details</button>
              
                {% endif %}
              </div>
            </div>

        </form>


        {% endblock body%}
      </div>
    </div>


  


  </div>
</div>

profiles/templates/profiles/updateuser.html
<!-- <form action="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update User</button>
</form> -->

<form method="POST" action="" enctype="multipart/form-data">
  <input
    type="hidden"
    name="csrfmiddlewaretoken"
    value="dl6pLGajuynReAEaYlHsUwfcGs0XosHAM44eRNBXHOeZgcNRVK3aTenZRytMGmIW"
  />
  <p>
    <label for="id_user">User:</label>
    <select name="user" required id="id_user">
      <option value="">---------</option>

      <option value="1" selected>sajithpi</option>

      <option value="21">sajiradio</option>

      <option value="22">radio</option>
    </select>
  </p>
  <p>
    <label for="id_image">Image:</label> Currently:
    <a href="/media/profiles/SAJITH_P_I_1_QuHxXWG.jpg"
      >profiles/SAJITH_P_I_1_QuHxXWG.jpg</a
    ><br />
    Change:
    <input type="file" name="image" id="id_image" />
  </p>
  <p>
    <label for="id_gender">Gender:</label>
    <input
      type="text"
      name="gender"
      value="male"
      maxlength="100"
      required
      id="id_gender"
    />
  </p>
  <p>
    <label for="id_contact">Contact:</label>
    <input
      type="number"
      name="contact"
      value="949256259"
      required
      id="id_contact"
    />
  </p>
  <p>
    <label for="id_place">Place:</label>
    <input
      type="text"
      name="place"
      value="manjeri"
      maxlength="100"
      required
      id="id_place"
    />
  </p>
  <p>
    <label for="id_country">Country:</label>
    <input
      type="text"
      name="country"
      value="india"
      maxlength="100"
      required
      id="id_country"
    />
  </p>
</form>