feed/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "feed"

urlpatterns = [
   
    # path("",views.HomePage.as_view(),name="home"),
    path("",views.HomePage.as_view(),name="home"),
    path("<int:pk>/",views.PostDetailView.as_view(),name="detail"),
    path("find/",views.FindFriends.as_view(),name="find"),
    path("uploadPost/",views.UploadPost.as_view(),name="new_post"),
    path("like/",views.Like_post ,name="like_post"),
    path("delete/",views.delete_post,name="delete"),
    path("update/",views.updatePost,name="update"),
    path("search/",views.FindFriends.as_view(),name="search"),
    path("comment/",views.Comment_post,name="comment"),
    path("favorites/",views.AddFavorites,name="add_to_favorites"),
    path('search_rooms/',views.Search_Room,name="search_room"),
    path("notification/<int:notification_pk>/post/<int:post_pk>",views.post_notification,name="post_notification"),
    path("notification/<int:notification_pk>/user_profile/<str:user_pk>",views.user_profile_notification,name="user_profile_notification"),
    path("delete_comment/",views.delete_comment,name="delete_comment"),
    path("update_comment/",views.update_comment,name="update_comment"),
    path("add_story/",views.addStory,name="add_story"),
    path("view_story/",views.View_story,name="view_story"),
    path("story_seen_add/",views.Story_Seen_Add,name="story_seen_add"),
    path("story_seen/",views.Story_Seen,name="story_seen_eye"),
    path("chat/",views.ChatView,name="template"),
    path("notification_clear/",views.Notification_Clear,name="notification_clear"),


   
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path 
from . import views

app_name = "profiles"

urlpatterns = [
 
    
    path("profile/<str:user_id>", views.ProfilePersonalUpdate.as_view(), name="update"),

    path("profile/<str:id>", views.ProfileLoginUpdate.as_view(), name="updatelogin"),
   
    path("<str:username>/", views.ProfileDetailView.as_view(), name="user_profile"),

    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),

    path("til/templates/",views.PasswordsChangeView.as_view(),name="reset"),

    path('til/templates/account/',views.password_success,name="password_success"),

    path('inbox/chat/',views.ListThreads.as_view(),name="inbox"),

    path('inbox/create_thread/',views.CreateThread.as_view(),name="create_thread"),

    path('inbox/<int:pk>/',views.ThreadView.as_view(),name="thread"),

    path('inbox/<int:pk>/<int:message_pk>',views.ReadMessage.as_view(),name="read_message"),

    path('inbox/<int:pk>/create_message/',views.CreateMessage.as_view(),name="create_message"),

    path("<str:username>/welcome/",views.welcome_email,name="welcome"),
    
]

til/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls, views
from chat import urls as chat_urls



urlpatterns = [
    path('admin/',include('admin_honeypot.urls', namespace="admin_honeypot")),
    path('socialbooksecurelogin/', admin.site.urls),
    path("",include(feed_urls, namespace="feed")),
    path("",include(profiles_urls, namespace="profiles")),
    url("",include("allauth.urls")),
    path('accounts/', include('allauth.urls')),
    path("",include(chat_urls,namespace="chat")),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

feed/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import IntegerField
from profiles.models import  Profile
from django.db.models.deletion import CASCADE
from sorl.thumbnail import ImageField
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class Post(models.Model):
    text = models.CharField(max_length=255)
    date_time = models.DateTimeField(auto_now=True)
    photo = ImageField(upload_to="uploads/posts")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,

    )
    likes = models.ManyToManyField(User, related_name="likes")
    


    def __str__(self):
        return self.text[0:100]

    @property
    def total_like(self):
        return self.likes.all().count()


STATUS =  (
        ('Like','Like'),
        ('Dislike','Dislike'),
    )


     
    
class Like(models.Model):
    user = models.ForeignKey(User,on_delete=CASCADE)
    post = models.ForeignKey(Post,on_delete=CASCADE)
    value = models.CharField(choices=STATUS,default='Like',max_length=9)
    
    def __str__(self):
       return str(self.post) 

class Stories(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=55,blank=True)
    created_time = models.DateTimeField(auto_now=True)
    photo = ImageField(upload_to="uploads/stories")
    viewers = models.ManyToManyField(Profile, related_name="viewers")
   
    # def __str__(self):
    #     return str(self.author.username + ' ') + str('- ' + self.text)

# class Stories_Seen(models.Model):
#     story = models.ForeignKey(Stories,on_delete=models.CASCADE)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)

 
class Comment(models.Model):
    
    user = models.ForeignKey(Profile,on_delete=CASCADE)
    post = models.ForeignKey(Post,on_delete=CASCADE)
    content = models.TextField(max_length=255)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.content)
        
class Favorites(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def  __str__(self):
        return self.user.username


class Notification(models.Model):

    notification_type = models.IntegerField()
    to_user = models.ForeignKey(User, related_name="notification_to", on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(User, related_name="notification_from" ,on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, related_name="+", on_delete=models.CASCADE,null=True, blank=True)
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    date = models.DateTimeField(auto_now_add=True)
    user_has_seen = models.BooleanField(default=False)

feed/forms.py
from django import forms
from django.forms import fields
from django.forms.models import ALL_FIELDS
from .models import Comment, Post
from feed import models

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text','photo')

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='test label',
                            widget=forms.TextInput(attrs={'placeholder':'Add a comment here'}))
    class Meta:
        model = Comment
        fields = ('content',)

class CommentForms(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user',)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

feed/views.py
from ast import Store
from email import message
from django import views
from django.contrib.auth.models import User
from django.http.response import HttpResponseBadRequest, JsonResponse,HttpResponse
from django.template import context
from django.views.generic import TemplateView
from django.views.generic import  DetailView, View,ListView,FormView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from profiles.models import Profile
from feed.models import Favorites
from .models import Comment, Notification, Post,Like, Stories
from django.db.models import Q
import datetime
from chat.models import Chat, RoomChat
from django.shortcuts import get_object_or_404, redirect, render
from django.http import JsonResponse
from .forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class HomePage(LoginRequiredMixin,TemplateView):
    http_method_names = ["get"]
    template_name = "feed/homepage.html"
    # login_url = 'account/login.html'
    # redirect_field_name = 'feed/homepage.html'
    # model = Post
    # context_object_name = "posts"
    # queryset = Post.objects.all().order_by('-id')[0:30]
 

   
    def dispatch(self, request, *args, **kwargs):

            if request.user.is_authenticated:
                self.request = request
            
                return super().dispatch(request, *args, **kwargs)

            return render(request,'feed/homepage.html')
            # return render(request,'includes/login.html')

    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)


        comment_form = CommentForm()
        posts= Post.objects.all().order_by('-id')[0:30]
        profile= Profile.objects.get(user=self.request.user)
        user = User.objects.get(id=self.request.user.id)
        favorites = Favorites.objects.filter(user__id = self.request.user.id)
        try:
            stories = Stories.objects.order_by('author')
          
            for story in stories:
                created_date = story.created_time.day
                current_date = datetime.datetime.now().day
                print("current date:",current_date)
                print("Created Day:",created_date)
                story = Stories.objects.get(id=story.id)
                if current_date > created_date :
                     story.delete()
                     print("Story Time Exeeded 1 Day")
                else:
                    print("Story Available")
        except Stories.DoesNotExist:
            pass

        # Fetching chat History
        try:
            rooms = RoomChat.objects.filter(Q(sender =self.request.user.username) | Q(receiver = self.request.user.username))
            chats = []
            for room in rooms:
                chat = Chat.objects.filter(room = room).last()
                chats.append(chat)
                
            for i in chats:
                print(i.content)
        except:
            pass
        user_story = Stories.objects.filter(author__id=self.request.user.id).first()
        
        context['posts'] = posts
        context['comment_form'] = comment_form
        context['profile'] = profile
        context['rooms'] = rooms
        context['chats'] = chats
        context['stories'] = stories
        context['user_story'] = user_story
        context['favorites'] = favorites
        
        return context
class PostDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "feed/detail.html"
    model = Post
    context_object_name = "post"
   

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        no_of_likes = get_object_or_404(Post, id = self.kwargs['pk'])
        
        # total_likes = no_of_likes.total_like()

        liked = False
        if no_of_likes.likes.filter(id = self.request.user.id).exists():
            liked = True 
        

        # context['total_likes'] = total_likes
        context['liked'] = liked
        return context


class UploadPost(LoginRequiredMixin,CreateView):
    model = Post
    # http_method_names = ["get"]
    template_name = "feed/uploadPost.html"
    fields = ['text','photo']
    success_url ="/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request,*args,**kwargs)

    def form_valid(self, form):
      
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        post =  Post.objects.create(
            text = request.POST.get("text"),
            photo = request.FILES.get("photo"),
            author = request.user,
        )
        return render(
            request,
            "includes/post.html",
            {
                "post":post,
            },
            content_type="application/html"
        )

class FindFriends(ListView):
    model = Post
    http_methods_name = ['get']
    template_name = "feed/findfriends.html"

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)

        if 'keyword' in self.request.GET:
            keyword = self.request.GET['keyword']
        
          
            if keyword:  
                context['user_details'] = Profile.objects.order_by('-user').filter(user__username__icontains = keyword)
                context['keyword'] = keyword
                return context
        else:
            context['user_details'] = Profile.objects.all()
            return context


def addStory(request):
    if request.method == 'POST':
        image = request.FILES.get('photo')
        description = request.POST.get('text')
        user = User.objects.get(id = request.user.id)
        print("text:",description)
        print("image:",image)
        print("username:",user.username)
        stories = Stories.objects.create(
            text = description,
            photo = image,
            author = user
        )
        stories.save()
        return JsonResponse({"message":"success"})
    return JsonResponse({'message':'not'})

# def View_story(request):
#     if request.method == 'POST':
#         story_id = request.POST.get('story_id')
#         story_author = request.POST.get('story_author')
#         print("story_id:",story_id)
#         print("story_author:",story_author)
#         story = Stories.objects.filter(author__username=story_author).order_by("-created_time").values()
   
#         story_seen = Stories.objects.filter(author__username=story_author).order_by("created_time")
#         # print("story count:",story))
#         story_count = story.count()
#         user = Stories.objects.get(id= request.user.id)
#         # story.viewers.add(user)
#         return JsonResponse({'message':'success','story':list(story),'count':story_count,'username':user.username})

    
    # return JsonResponse({"message":"not"})

def View_story(request):
    if request.method == 'POST':
        story_id = request.POST.get('story_id')
        story_author = request.POST.get('story_author')
        print("story_id:",story_id)
        print("story_author:",story_author)
        story = Stories.objects.filter(author__username=story_author).order_by("-created_time").values()
        story_seen = Stories.objects.filter(author__username=story_author).order_by("created_time")
        a = []
        for st in story_seen:
            a.append(st.author_id)
            print("id",a)
        # print("story count:",story))
        story_count = story.count()
        user = User.objects.get(id= request.user.id)
        # story.viewers.add(user)
        return JsonResponse({'message':'success','story':list(story),'count':story_count,'username':user.username})
    return JsonResponse({"message":"not"})

def Story_Seen(request):
    if request.method == 'POST':
        story_id = request.POST.get('story_id')
        story_caption = request.POST.get('story_caption')
        print("story_id:",story_id)
        print("story_caption",story_caption)
        story = Stories.objects.get(text=story_caption)
        viewers = story.viewers.all()
        viewers_count = viewers.count()
        print("viewers:",viewers)
        print("viewers count:",viewers_count)
        # print("story:",list(story))
        view_username = []
        view_user_dp = []
        for i in viewers:
            print(i.user.username)
            print(i.image.url)
            view_username.append(i.user.username)
            view_user_dp.append(i.image.url)

        return JsonResponse({"message":"success",'view_username':view_username,'view_user_dp':view_user_dp,'viewers_count':viewers_count})
        
    return JsonResponse({"message":"not"})
def Story_Seen_Add(request):
    if request.method == 'POST':
        story_id = request.POST.get('story_id')
        story_text = request.POST.get('story_text')
        user = Profile.objects.get(user__id=request.user.id)
        story = Stories.objects.get(text=story_text)
        print("story_text:",story_text)
        print("story_id",story_id)
        if user in story.viewers.all():
            story.viewers.remove(user)
        else:
            story.viewers.add(user)
        # print("story:",list(story))
        return JsonResponse({'message':'success',"story_id":story_id})
    return JsonResponse({"message":"not"})
def Like_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_object = Post.objects.get(id=post_id)
        user = User.objects.get(id = request.user.id)
        post_author = User.objects.get(username=post_object.author.username)
       
        profile = Profile.objects.get_or_create(user=user)
        # profiles = Profile.objects.filter(user__username = post_object.author.username)

feed/templates/feed/detail.html
{% extends 'base.html' %}


{% block title %}
    Detail View
{% endblock title %}
    

{% block body %}
<div class="fixed top-0 left-0 right-0 z-50">
    {% include 'includes/navbar.html' %}
  </div>
  <div class="mt-24 z-20 w-1/2 mx-auto">
  
    {% if request.user.is_authenticated %}
  
        {% include 'includes/post.html' with post=post show_detail_link=False show_comment_list=True%}
    {% else %}
        {% include 'includes/login.html' %}
    {% endif%}
</div>

{% endblock body %}
    

feed/templates/feed/findfriends.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Find Friends
{% endblock title %}


{% block body %}
  <div class="fixed top-0 left-0 right-0 z-50">
    {% include 'includes/navbar.html' %}
  </div>
    <div class="py-10 h-screen px-2 mt-20">
        <div class="max-w-md mx-auto bg-gray-50 shadow-lg rounded-lg overflow-hidden md:max-w-lg">
            <div class="w-full">
                {% if request.user.is_authenticated %}
                    {% if user_details %}
                        <div class="w-full p-4">
                            <div class="flex-auto flex items-center justify-center ">
                                <div class="ml-8">
                                    <form action="{% url 'feed:search' %}" method="get" >
                                        <label for="search" class="sr-only text-xs md:text-sm">Search</label>
                                        <div class="w-full h-7 sm:w-full md:h-10  bg-white border rounded-lg flex justify-between items-center relative mx-1 pl-3  pr-2">
                       
                                            <input type="search" name="keyword" id="search" placeholder="{% if keyword %}{{keyword}}{% else %}Search{% endif %}"
                                                class="w-full outline-none focus:outline-none active:outline-none  "/>
                                            <button type="submit" class=" outline-none focus:outline-none active:outline-none self-center">
                                                <div class="items-center mt-1 ">
                                                    <i class='bx bx-search-alt-2 text-base md:text-xl' ></i>
                                                </div>
                                                
                                            </button>
                                       
                                      </div>
                                    </form>
                                </div>
                            </div>
                            <ul>
                                <div class="text-xs text-gray-700 font-semibold my-2">{{user_details.count}} Results</div>
                                {% for user in user_details %}
                                <a href="{% url 'profiles:user_profile' user.user.username %}">
                                    <li class="flex justify-between items-center bg-gray-50 hover:bg-gray-200 shadow-md mt-2 p-2 hover:shadow-lg rounded cursor-pointer transition">
                                        <div class="flex ml-2 items-center">
                                             <!-- <img src="{{user.image.url}}" width="40" height="25" class="rounded-full"> -->
                                           
                                             {% thumbnail user.image "100x100" crop="center" as img %}
                                                <img  src="{{ img.url }}"class="rounded-full border-solid border-white border-2 w-12 h-12">
                                            {% endthumbnail %}
                                           
                                            <div class="flex flex-col ml-2 justify-center"> 
                                      <span class="font-medium text-black">{{user | title}}</span>
                                               
                                                <span class="text-xs text-gray-400">
                                                    {% if user.bio %}
                                                        {{user.bio | title}}
                                                    {% endif %}
                                                </span>
                                                 <span class="text-xs text-gray-400  truncate w-32">
                                                    {% if user.country %}
                                                        {{user.country | title}},
                                                    
                                                    {% endif %}
                                                    
                                                    {% if user.state %}
                                                        {{user.state | title}},
                                                
                                                    {% endif %}
                                                        
                                                    {% if user.place %}
                                                        {{user.place | title}}
                
                                                    {% endif %}

                                                    
                                                </span> 
                                            </div>
                                        </div>
                                    </li>
                                </a>
                                {% endfor %} 
                            </ul>
                        </div>
                    {% else %}
                    
                        <div class="py-1 mt-2 text-md md:text-xl mx-1 text-center">
                            <i class='block bx bx-sad text-blue-700 text-4xl'></i>
                            <span class="block">No Results Found,Search Again</span>
                        </div>
                        <div class="flex-auto flex items-center justify-center mb-4">
                            <div class="">
                                <form action="{% url 'feed:search' %}" method="get" >
                                    <label for="search" class="sr-only text-xs md:text-sm">Search</label>
                                    <div class="w-full h-7 sm:w-full md:h-10  bg-white border rounded-lg flex justify-between items-center relative mx-1 pl-3  pr-2">
                   
                                        <input type="search" name="keyword" id="search" placeholder="{{keyword}}"
                                            class="w-full outline-none focus:outline-none active:outline-none  "/>
                                        <button type="submit" class=" outline-none focus:outline-none active:outline-none self-center">
                                            <div class="items-center mt-1 ">
                                                <i class='bx bx-search-alt-2 text-base md:text-xl' ></i>
                                            </div>
                                            
                                        </button>
                                   
                                  </div>
                                </form>
                            </div>
                        </div>
                    {% endif %}
                {% else %}
                    {% include 'includes/login.html' %}
                {% endif %} 
            </div>
        </div>
    </div>
{% endblock body %}

    
    

feed/templates/feed/show_notification.html
<!-- component -->
<!-- Facebook notification -->
<style>
        .text-blue {
            color: #1876f2;
        }
    </style>
{% load thumbnail %}
<div class="text-end pr-4 bg-gray-100">

</div>

{% if notifications %}



    
<div class="overflow-y-scroll max-h-96">

    
    <div class="flex w-full justify-between">

        <button id="notification_clear" data-notification-clear-url="{% url 'feed:notification_clear' %}" class="text-xs md:text-sm font-semibold text-blue-700">Clear All</button>
        <button @click="dropdownOpen = !dropdownOpen"  class="bg-slate-100 p-1 mr-4">
            <i class="bi bi-x-circle text-blue-500"></i>
        </button>
    </div>
    
    {% for notification in notifications %}
        
        {% if notification.notification_type == 1 or notification.notification_type == 2 or notification.notification_type == 3  %}
        
            {% if notification.from_user is not notification.to_user %}
                    
                <div class="bg-gray-100  pl-1 md:pl-4 py-1 rounded-lg shadow-md max-w-md border-b notification_list">
                  
                    <div class="flex items-center  hover:bg-gray-100 rounded-lg  py-1 cursor-pointer">
                        {% if notification.post %}

                        
                                    <div class="rounded-full p-0.5  bg-gradient-to-b from-blue-400 via-green-500 to-indigo-700 ">
                                        <div class="rounded-full wrapper overflow-hidden h-9 w-9">
                                          <button>
                                            <a href="{% url 'feed:user_profile_notification' notification.pk notification.from_user.id %}">
                  
                                            {% thumbnail notification.from_user.profile.image "39x39" crop="center" as im %}
                                                <img src="{{ im.url }}" class="object-scale-down rounded-full border-solid border-white border-2">
                                              {% endthumbnail %}
                                              
                                            </a>
                                           
                                          </button>
                                        </div>
                                        
                                      </div>

                                    <div class="ml-3">
                                    
                                        {% if notification.notification_type == 1 %}
                                            <p class="text-xs md:text-sm m-auto "><span class="font-bold">{{notification.from_user | capfirst }}</span> Liked on your post</p>
                                        {% elif notification.notification_type == 2%}
                                            <p class="text-xs md:text-sm m-auto"><span class="font-bold">{{notification.from_user | capfirst }}</span> Commented on your post</p>
                    
                                        {% endif %}
                                    </div>
                                    <div class="flex flex-shrink-0 px-3 w-20 md:w-auto">
                                        <a href="{% url 'feed:post_notification' notification.pk  notification.post.pk %}">
                                        {% thumbnail notification.post.photo "59x59" crop="center" as im %}
                                                                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                                                                        class="object-scale-down">
                                        {% endthumbnail %}
                                        </a>
                                    </div>
                    
                    
                        
                        {% elif notification.notification_type == 3 %}
                            
                            <div class="flex flex-shrink-0 items-end">
                                <a href="{% url 'feed:user_profile_notification' notification.pk notification.from_user.id %}">
                                {% thumbnail notification.from_user.profile.image "39x39" crop="center" as im %}
                                                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                                                                class="rounded-full object-scale-down">
                                {% endthumbnail %}
                                </a>
                            </div>
                            <div class="m-auto pl-2">
                                <p class="text-xs md:text-sm m-auto"><span class="font-bold">{{notification.from_user | capfirst}}</span> Started Following You </p>
                                <!-- <small class="text-xs text-gray-500 font-semibold h-0.5">{{notification.date | timesince }} a few seconds ago</small>  -->
                            </div>   
                            <div class="flex flex-shrink-0 px-2 bg-white border-2 mr-1 md:mr-4">
                            
                                <span class="text-xs md:text-sm text-black font-semibold">Following</span> 
                            </div>   
                        {% endif %}
                            
                    
                    </div>
                    <div class="text-left"><small class="text-xs text-gray-500 font-semibold h-0.5">{{notification.date | timesince }} a few seconds ago</small> </div>
                </div>   
            {% endif %}
        {% endif %}
            
    {% endfor %}
    
</div>
{% endif %}

feed/templates/feed/uploadPost.html
{% extends 'base.html' %}


{% block title %}
    Upload new post
{% endblock title %}


{% block body %}
    <form method="POST" action="." enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
       
        <button type="submit">Upload File</button>
      
    </form>
  
{% endblock body %}
    