chat/urls.py
import imp
from django.urls import path

from chat import views

app_name="chat"

urlpatterns = [
    path("chat/index/",views.Index.as_view(),name="index"),
    path("chat/<str:room_name>/",views.Room.as_view(),name="room"),
    path("chat/is_read/<str:room_name>/",views.MessageReadSet.as_view(),name="message"),
    path("chat/is_read/<str:room_name>/sendPhoto/",views.Send_Image,name="send_image"),
    path("chat/<str:room_name>/delete/",views.Delete_Message,name="delete_message"),
 
    
]

feed/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "feed"

urlpatterns = [
   
    # path("",views.HomePage.as_view(),name="home"),
    path("",views.HomePage.as_view(),name="home"),
    path("<int:pk>/",views.PostDetailView.as_view(),name="detail"),
    path("find/",views.FindFriends.as_view(),name="find"),
    path("uploadPost/",views.UploadPost.as_view(),name="new_post"),
    path("like/",views.Like_post ,name="like_post"),
    path("delete/",views.delete_post,name="delete"),
    path("update/",views.updatePost,name="update"),
    path("search/",views.FindFriends.as_view(),name="search"),
    path("comment/",views.Comment_post,name="comment"),
    path("favorites/",views.AddFavorites,name="add_to_favorites"),
    path('search_rooms/',views.Search_Room,name="search_room"),
    path("notification/<int:notification_pk>/post/<int:post_pk>",views.post_notification,name="post_notification"),
    path("notification/<int:notification_pk>/user_profile/<str:user_pk>",views.user_profile_notification,name="user_profile_notification"),
    path("delete_comment/",views.delete_comment,name="delete_comment"),
    path("update_comment/",views.update_comment,name="update_comment"),
    path("add_story/",views.addStory,name="add_story"),
    path("view_story/",views.View_story,name="view_story"),
    path("story_seen_add/",views.Story_Seen_Add,name="story_seen_add"),
    path("story_seen/",views.Story_Seen,name="story_seen_eye"),
    path("chat/",views.ChatView,name="template"),
    path("notification_clear/",views.Notification_Clear,name="notification_clear"),


   
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

profiles/urls.py
from django.urls import path 
from . import views

app_name = "profiles"

urlpatterns = [
 
    
    path("profile/<str:user_id>", views.ProfilePersonalUpdate.as_view(), name="update"),

    path("profile/<str:id>", views.ProfileLoginUpdate.as_view(), name="updatelogin"),
   
    path("<str:username>/", views.ProfileDetailView.as_view(), name="user_profile"),

    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),

    path("til/templates/",views.PasswordsChangeView.as_view(),name="reset"),

    path('til/templates/account/',views.password_success,name="password_success"),

    path('inbox/chat/',views.ListThreads.as_view(),name="inbox"),

    path('inbox/create_thread/',views.CreateThread.as_view(),name="create_thread"),

    path('inbox/<int:pk>/',views.ThreadView.as_view(),name="thread"),

    path('inbox/<int:pk>/<int:message_pk>',views.ReadMessage.as_view(),name="read_message"),

    path('inbox/<int:pk>/create_message/',views.CreateMessage.as_view(),name="create_message"),

    path("<str:username>/welcome/",views.welcome_email,name="welcome"),
    
]

til/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls, views
from chat import urls as chat_urls



urlpatterns = [
    path('admin/',include('admin_honeypot.urls', namespace="admin_honeypot")),
    path('socialbooksecurelogin/', admin.site.urls),
    path("",include(feed_urls, namespace="feed")),
    path("",include(profiles_urls, namespace="profiles")),
    url("",include("allauth.urls")),
    path('accounts/', include('allauth.urls')),
    path("",include(chat_urls,namespace="chat")),
   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

feed/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import IntegerField
from profiles.models import  Profile
from django.db.models.deletion import CASCADE
from sorl.thumbnail import ImageField
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class Post(models.Model):
    text = models.CharField(max_length=255)
    date_time = models.DateTimeField(auto_now=True)
    photo = ImageField(upload_to="uploads/posts")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,

    )
    likes = models.ManyToManyField(User, related_name="likes")
    


    def __str__(self):
        return self.text[0:100]

    @property
    def total_like(self):
        return self.likes.all().count()


STATUS =  (
        ('Like','Like'),
        ('Dislike','Dislike'),
    )


     
    
class Like(models.Model):
    user = models.ForeignKey(User,on_delete=CASCADE)
    post = models.ForeignKey(Post,on_delete=CASCADE)
    value = models.CharField(choices=STATUS,default='Like',max_length=9)
    
    def __str__(self):
       return str(self.post) 

class Stories(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=55,blank=True)
    created_time = models.DateTimeField(auto_now=True)
    photo = ImageField(upload_to="uploads/stories")
    viewers = models.ManyToManyField(Profile, related_name="viewers")
   
    # def __str__(self):
    #     return str(self.author.username + ' ') + str('- ' + self.text)

# class Stories_Seen(models.Model):
#     story = models.ForeignKey(Stories,on_delete=models.CASCADE)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)

 
class Comment(models.Model):
    
    user = models.ForeignKey(Profile,on_delete=CASCADE)
    post = models.ForeignKey(Post,on_delete=CASCADE)
    content = models.TextField(max_length=255)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.content)
        
class Favorites(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def  __str__(self):
        return self.user.username


class Notification(models.Model):

    notification_type = models.IntegerField()
    to_user = models.ForeignKey(User, related_name="notification_to", on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(User, related_name="notification_from" ,on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, related_name="+", on_delete=models.CASCADE,null=True, blank=True)
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    date = models.DateTimeField(auto_now_add=True)
    user_has_seen = models.BooleanField(default=False)

til/models.py
from django.db import models

# Create your models here.

feed/forms.py
from django import forms
from django.forms import fields
from django.forms.models import ALL_FIELDS
from .models import Comment, Post
from feed import models

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text','photo')

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='test label',
                            widget=forms.TextInput(attrs={'placeholder':'Add a comment here'}))
    class Meta:
        model = Comment
        fields = ('content',)

class CommentForms(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user',)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

til/views.py
from django.shortcuts import render

# Create your views here.

til/templates/includes/alert.html
{% if messages %}


    {% for message in messages %}
    
    {% if 'sign' not in message %}
        
        <div id="message" class="container">

        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
            <button type="button" class="close text-sm md:text-base" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </div>
        
        </div>  
    {% endif %}
        
{% endfor %}
{% endif %}
 

til/templates/includes/background.html
<div
	class="mx-auto flex justify-center items-center filter blur-2xl animate-pulse duration-500 transition w-1/5 md:w-3/5  ">
	<div class=" mr-10 flex relative">
		<div class=" rounded-full absolute top-20 right-0">

		</div>
		<div class=" rounded-full bg-gradient-to-r to-pink-500 from-indigo-500 absolute md:flex hidden">

		</div>
	</div>
	<!-- Right Side -->
	<div class="flex flex-col absolute top-8 right-10 space-y-1">

		<div class=" rounded-full bg-gradient-to-r to-pink-500 via-red-500 from-indigo-500 absolute right-16 top-10">

		</div>
	</div>
	<div class="flex flex-col absolute bottom-8 right-10 space-y-1">

		<div class=" rounded-full bg-gradient-to-r to-pink-500 from-indigo-500 absolute right-16 bottom-10">

		</div>
	</div>
	<!--  Left side -->
	<div class="flex flex-col space-y-1 filter animate-pulse duration-500">
		<div class=" bg-gradient-to-r to-indigo-500 from-blue-500 absolute top-20 left-20">

		</div>
		<div class="p-10 bg-gradient-to-r to-indigo-500 from-blue-500 absolute bottom-20 right-20">

		</div>
	</div>
</div>

til/templates/includes/navbar.html
{% load custom_tags %}
   <!-- Navigation Bar -->
  
 

   <nav class="w-auto bg-white shadow-lg border-t-1 shadow-indigo-500/40 shadow border-b border-gray-400 absolute inset-x-0 top-0 h-16 z-30  ">
       
    <div class="w-auto border-gray-400 ml-8 md:ml-64 z-50">
        {% include 'includes/alert.html' %}
       </div>
   
    <div class="flex justify-between h-16">
        <div class="flex w-11 md:w-14  ">
            <div class="flex-shrink-0 flex items-center">
                <a href="{% url 'profiles:welcome' user.username %}"> <div class="text-sm md:text-2xl capitalize text-indigo-500 ml-1 md:ml-4 ">SocialBook</div> </a>
            </div>
        </div>
        <!-- Search Button -->
        <div class="flex-auto flex items-center justify-center ">
            <div class="ml-8">
                <form action="{% url 'feed:search' %}" method="get" >
                    <label for="search" class="sr-only text-xs md:text-sm">Search</label>
                    <div class="w-28 h-7 sm:w-full md:h-10  bg-white border rounded-full flex justify-between items-center relative mx-1 pl-3  pr-2">
   
                        <input type="search" name="keyword" id="search" placeholder="Search"
                            class="w-full outline-none focus:outline-none active:outline-none  "/>
                        <button type="submit" class=" outline-none focus:outline-none active:outline-none self-center">
                            <div class="items-center mt-1 ">
                                <i class='bx bx-search-alt-2 text-base md:text-xl' ></i>
                            </div>
                            
                        </button>
                   
                  </div>
                </form>
            </div>
        </div>

        <!-- icons-->
        <div class="lg:ml-4 flex items-center self-center mr-0 md:mr-3">
            <!-- TODO:Home Icon -->
            <button
                class="flex-shrink-0 pr-1 md:pr-4 border-transparent text-gray-700 rounded-full hover:text-gray-600 focus:outline-none ">
                <a href="{% url 'feed:home' %} "
                class="flex flex-col md:flex-row items-center h-12  text-gray-500 hover:text-gray-800 ">
                <span class="inline-flex items-center content-start md:content-center  h-12 text-gray-400"><i
                    class="bx bx-home text-indigo-500 text-lg md:text-2xl"></i></span>
      
              </a>
            </button>
            {% if request.user.is_authenticated %}

            <!-- Chat Rooms -->
                <button
                    class="flex-shrink-0 pr-1 md:pr-4 border-transparent text-gray-700 rounded-full hover:text-gray-600 focus:outline-none">
                    <a href="{% url 'chat:index' %}"
                    class="flex flex-col md:flex-row items-center h-12 transform  text-gray-500 hover:text-gray-800 ">
                    <span class="inline-flex items-center content-start md:content-center w-6 h-12 text-gray-400"><i
                        class="bx bxs-chat text-indigo-500 text-lg md:text-2xl"></i></span>
                    <!-- <div class="text-xs md:text-sm font-medium  hidden md:block">Profile</div> -->
                </a>
                </button>

        

             <!-- #Notification List -->

             <div x-data="{ dropdownOpen: false }" class="relative my-36  pr-1 md:pr-4">
                <button @click="dropdownOpen = !dropdownOpen" class="relative flex-shrink-0 pt-1 border-transparent text-gray-700 rounded-full hover:text-gray-600 focus:outline-none">
                    <i class='bx bx-notification text-indigo-500 text-xl md:text-2xl'></i>
                    <span class="absolute inset-0 object-left-top -ml-6">
                        <div class="inline-flex items-center px-0.5 py-0 border-2 border-white rounded-full text-xs font-semibold leading-4 bg-red-500 text-white">
                         {{notification_count}}
                        </div>
                      </span>
                </button>
             
              
                <div x-show="dropdownOpen" @click="dropdownOpen = false" class="fixed inset-0 h-full w-full z-10"></div>
              
                <div x-show="dropdownOpen" class="absolute right-0 mt-2 py-2 w-64 pl-8 md:pl-0 md:w-80 bg-white rounded-md shadow-xl z-50 ">
                  {% show_notifications %}
                
                  </a>
                  
                </div>
            </div>

                <!-- New Post -->
                <!-- <button
                class="flex-shrink-0 pr-0.5 md:pr-4 border-transparent text-gray-700 rounded-full hover:text-gray-600 focus:outline-none "
                aria-label="Notifications">
                    <a href="{% url 'feed:new_post' %}"
                    class="js-model-icon flex flex-col md:flex-row items-center h-12 text-gray-500 hover:text-gray-800 ">
                    <span class="inline-flex items-center content-start md:content-center  h-12  text-gray-400"><i
                        class="bx bx-message-alt-add text-indigo-500 text-xl md:text-2xl"></i></span>
                
                    </a>
                </button> -->

                <!-- Logout -->
                <button
                    class="flex-shrink-0 pr-0.5 md:pr-4 border-transparent text-gray-700 rounded-full hover:text-gray-600 focus:outline-none "
                    aria-label="Notifications">
                    <a href="{% url 'account_logout' %}"
                    class="flex flex-col md:flex-row items-center h-12 text-gray-500 hover:text-gray-800 ">
                    <span class="inline-flex items-center content-start md:content-center  h-12  text-gray-400"><i
                        class="bx bx-log-out text-indigo-500 text-lg md:text-2xl"></i></span>
                
                </a>
                </button>
            {% endif %}




        </div>
    </div>
   
</nav>

til/templates/includes/post.html
{% load thumbnail %}
{% load post_tags %}
{% load static %}
<script defer src="https://unpkg.com/alpinejs@3.1.1/dist/cdn.min.js"></script>
<style>
	@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap');
	@import url('https://fonts.googleapis.com/css2?family=Varela&display=swap');
	@import url('https://fonts.googleapis.com/css2?family=Karla:wght@200&display=swap');

	* {
		font-family: 'Nunito', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
		direction: ltr;
		font-weight: 500;
	}
</style>


	
{% include 'includes/background.html' %}

<div class="flex justify-center  md:mb-1 mt-1 bg-white shadow-lg shadow-indigo-500/40  rounded items-center  border  w-full"
	x-data="{
        comment : false,
    }">
	
	<div class="h-full relative post ">
	
		<div class="px-2 py-2">
			<div class="flex justify-between items-center">
				<div class=" flex">
					<a href="{% url 'profiles:user_profile' post.author.username %}">
					<div class="bg-transparent flex">
						<div class="bg-slate-200 w-6 md:w-10 ">
						
								{% thumbnail post.author.profile.image "51x51" crop="center" as im %}
								<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
									class="rounded-full object-scale-down ">
								{% endthumbnail %}
							
						</div>
						<!-- <img class="w-12 h-12 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"/> -->
						<div class="self-center ml-2 mt-0.5 text-xs md:text-base 
									font-bold text-black dark:text-gray-100 
									object-scale-down capitalize">
									
										{{post.author.username}}
									
            			</div>
          			</div>
				</a>
				</div>
						{% if post.author.username == user.username %}
						<div class=" flex">

								<form action="" method="POST" id="{{post.id}}" class="">
									{% csrf_token %}
									<button id="delete-box{{post.id}}" type="button"
										class="relative p-0 md:p-2 focus:outline-none border-none bg-gray-100 rounded-full">
										<a class="delete-icon" href="{% url 'feed:delete' %}" id="{{post.id}}"">
										<i class='bx bx-trash text-sm md:text-base'></i>
										</a>
								</button>
								<!-- TODO:Delete form -->
			
							</form>
							<button id=" edit-box{{post.id}}" type="button"
											class="relative p-0 md:p-2 mx-1 md:mx-3 focus:outline-none border-none bg-gray-100 rounded-full">
											<a class="update-icon" id="{{post.id}}">
												<i class='bx bxs-edit text-sm md:text-base'></i>
												</a>
							</button>
							<!-- Favourites -->
							<button id=" favourites-box{{post.id}}" type="button"
											class="relative p-0 md:p-2 mr-0 md:mr-3 focus:outline-none border-none bg-gray-100 rounded-full">
											
										
											<!-- Checking whether the post is marked as favorites using post tags -->
											{% favorites_post_check post.id request.user.id as fav %}
										
											<a class="favorite-icon" id="{{post.id}}" href="{% url 'feed:add_to_favorites' %}">
															<span id="favorite-icon{{post.id}}">
																<i class='{{fav}} text-sm md:text-base'></i>
															</span>
											</a>
										
							</button>
							
						</div>
						{% endif %}
					</div>
				</div>
		
				{% if show_detail_link %}
				<div class="post-img{{post.id}} relative w-full h-full bg-slate-200">
					<a href="{% url 'feed:detail' post.id %}">
						<img id="postImg{{post.id}}" src="{{ post.photo.url }}" alt="SocialBook"
							class="w-full h-full">
					</a>
				</div>
				{% else %}
				<div class="post-img{{post.id}} relative w-full h-full bg-slate-200">
				
					<img src="{{ post.photo.url }}" alt="SocialBook"
						class="w-full h-full">

				</div>

				{% endif %}
				
				<!-- TODO:Like Comment Buttons -->
				<div class="Like_Comment">
					<div class="mx-3 md:mx-5">
						<!-- TODO:System Like and tools Feed -->
						<div class="flex justify-between items-start py-0 md:py-2 h-6 md:h-8 my-1 md:mt-3">
							<div class="flex space-x-2 items-center items-baseline">
								<!-- TODO:LIke Div -->

								<div class="mr-1 md:mr-5" action="{% url 'feed:like_post' %}" method="POST" id="{{post.id}}" >
				
									<input class="like_post_id" type="hidden" name='post_id' value="{{post.id}}">

									 <button id="{{post.id}}" class="like-button flex font-bold 
												rounded hover:text-blue-500 text-lg md:text-xl lg:text-3xl"
												 type="button" data-like-url="{% url 'feed:like_post' %}"> 
												<div id="like_div{{post.id}}">
													
													{% if request.user not in post.likes.all %}
														<i id="like-icon{{post.id}}" class='bx bx-heart text-blue-500 '></i>
													{% else %}
														<i  id="like-icon{{post.id}}" class='bx bxs-heart text-red-500'></i>
													{% endif %}
														
												</div>
				
								
									</button>
								</div>
							
								<!-- TODO:Comment Button -->
								<input class="mr-1 md:mr-5" type="hidden" name='post_id' value="{{post.id}}" class="post_id_value">
								<div class="md:pr-0 pr-4">
									<button id="{{post.id}}" class="comment-button-icon font-bold text-lg md:text-xl lg:text-3xl
												rounded hover:text-blue-500">
										<a class="text-black"><span><i
													class='bx bx-comment-dots'></i></span></a>
										<div hidden class="text-xs md:text-sm text-gray-500 ">Comment</div>
										
									</button>
								</div>
								
							</div>
							
							
						</div>
							<!-- TODO:Getting  Number of likes -->
						<div class="flex Like_Count font-bold text-xs md:text-base">
								<input hidden type="text" id="like_count{{post.id}}" value="{{post.total_like}}">
								<div type="text" id="like-count{{post.id}}" class="font-bold pr-1 my-0 md:my-1 "
									>{{post.total_like}}</div>Likes
								
						</div>
						<!-- TODO:Post Text -->
						<div class="flex post-text mr-3 mt-0.5">
							<input type="hidden" class="post{{post.id}}" id="{{post.id}}" value="{{post.id}}">
									<span class="text-black-500 text-xs md:text-base font-bold">
												{{post.author.username|capfirst}}
									</span>
									<div id="post-text{{post.id}}"
										class="w-auto post-text{{post.id}} text-black-500  ml-1 text-xs md:text-base  capitalize mr-3 truncate">
										{{post.text}}
								</div>
						</div>
						<div class="font-normal text-xs text-gray-500 timesince py-1">
							<small>{{post.date_time |timesince }} ago</small>
						</div>
					
						<!-- TODO: Comment Section -->
						<div class="z-50 ">
							<input hidden name="post_id" value="{{post.id}}">
							<input hidden id="profile_img{{post.id}}" value="{{user.profile.image.url}}">
							<form action="" method="POST" class="comment-form" id="{{post.id}}"
								data-url="{% url 'feed:comment' %}" enctype='multipart/form-data'>
								{% csrf_token %}

								<div class="flex justify-between border-t items-center w-full border-b border-gray-300"
									:class="comment ? 'absolute bottom-0' : '' ">

									<div class="w-full" >
										<input id="comment-content{{post.id}}" type="text" name="content"
											placeholder="Add a comment here" required_id="id_content"
											class="comment-content{{post.id}} w-full text-xs md:text-sm py-2 px-0.5 md:px-3 rounded-none ">
									</div>
									<div class="w-20">
										<button
											class="comment-button{{post.id}} border-none text-xs md:text-sm px-4 bg-white py-2 text-blue-600 focus:outline-none"
											type="submit">Post</button>
									</div>
								</div>
							</form>
						</div>
					
						<!-- TODO:New Comment Section -->
						<input hidden id="comment_flag" value="{{show_comment_list}}">

						<div id="comment-container{{post.id}}" class=" pl-1  md:pl-4 ">
							<input hidden type="text" value="This is the comment "> 
						</div>
						<!-- End System Like and tools Feed -->
						<!-- TODO: Existing Comments Listing -->
					{% if show_comment_list == True %}
							<div class=" pl-1 py-1 md:pl-4  overflow-auto max-h-80" id="comment_list{{post.id}}">
								{% if post.comment_set.all %}
									{% for comment in post.comment_set.all reversed %}
									<div id="comment-container{{comment.id}}" class=" pl-1  md:pl-4 ">
										<input hidden type="text" value="This is the comment cona=asdadadsadas">
									</div>
										<div class="flex border-b border-gray-300 items-center comment_list" id="comments-list{{post.id}} ">
											<div class="flex  w-14 h-9 md:h-11 mx-auto justify-center">
												<a class="self-center" href="">
													<!-- {{comment.user.user.username}} -->
													{% thumbnail comment.user.user.profile.image "29x29" crop="center" as im %}
													<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
														class="rounded-full object-scale-down">
													{% endthumbnail %}
	
												</a>
											</div>
											
											
											
											<div class="flex-initial grow w-3/4" >
												
												{% if comment.user.user.username == user.username %}
													<div class="flex pl-1 w-full md:pl-3 text-sm md:text-base w-4/5 ">
														<textarea class="flex w-full w-4/5 h-7 rounded truncate" type="text" id="comment_content{{comment.id}}" value="{{comment.content}}" >{{comment.content}}</textarea>
													</div>
													
												{% else %}
												<div class="flex pl-1 w-full md:pl-3 text-sm md:text-base truncate">{{comment.content}}</div>
												{% endif %}
													
											</div>
											<div class="flex-initial w-1/4">
												
												{% if comment.user.user.username == user.username %}
													<div class=" flex justify-end">
														<form action="" method="POST" id="{{comment.id}}" class="">
															{% csrf_token %}
															<input hidden type="text" name="comment_user" id="comment_user{{comment.id}}" value="{{comment.user.user.username}}">
															<input hidden type="text" name="comment_user_id" id="comment_user_id{{comment.id}}" value="{{comment.user.user.id}}">
															<input hidden type="text" name="comment_content" id="comment_id{{comment.id}}" value="{{comment.content}}">
															<input type="hidden" name='post_id' value="{{post.id}}" class="post_id_value{{comment.id}}">
															<button id="delete-comment-box{{post.id}}" type="button"
																class="relative p-0 md:p-2 focus:outline-none border-none bg-gray-100 rounded-full">
																<a class="delete-comment-icon" href="{% url 'feed:delete_comment' %}" id="{{comment.id}}"">
																<i class='bx bx-trash'></i>
																</a>
															</button>
														<!-- TODO:Delete form -->
														<button id="edit-comment-box{{comment.id}}" type="button"
																	class="relative p-0 md:p-2 focus:outline-none border-none bg-gray-100 rounded-full">
																	<a class="update-comment-icon" href="{% url 'feed:update_comment' %}" id="{{comment.id}}">
																		<i class='bx bxs-edit'></i>
																		</a>
															</button>
									
														</form>
															
													</div>
												{% endif %}
											</div>






										</div>
										
										
									{% endfor %}
								{% endif %}
								<input hidden id="comment-count{{post.id}}" value="{{post.comment_set.all.count}}">
								{% if post.comment_set.all.count > 1 %}
									<a hidden href="{% url 'feed:detail' post.id%}">View ALl
										<span hidden id="comment_count_body{{post.id}}">{{post.comment_set.all.count}}</span> Comments
									</a>
								{% else %}
								<span hidden id="comment_count_body{{post.id}}">comments</span> Comments
								{% endif %}
							</div>

						<!-- TODO:If show comment list = False -->
					{% else %}
						<div class=" pl-1 md:pl-4 divide-y divide-slate-200">
							{% if post.comment_set.all %}
								{% for comment in post.comment_set.all reversed %}
									{% if forloop.counter < 3 %}
										<div class="flex my-1 " id="comments-list{{post.id}}">
											<div class="text-xs md:text-base font-bold ">{{comment.user.user.username}}</div>
											<div class="pl-1 md:pl-3 text-xs md:text-base self-center truncate">{{comment.content}}</div>
											<span></span>
										</div>
									{% endif %}
								{% endfor %}
								{% if post.comment_set.all.count > 1 %}
									<input  hidden id="comment-count{{post.id}}" value="{{post.comment_set.all.count}}">
										<a class="text-xs md:text-sm text-blue-500 my-3" href="{% url 'feed:detail' post.id%}">View ALl
											<span id="comment_count_body{{post.id}}">{{post.comment_set.all.count}}</span> Comments
										</a>
								{% endif %}
							{% else %}
							<input hidden id="comment-count{{post.id}}" value="1">
							<span  hidden id="comment_count_body{{post.id}}">No Comments</a>
						{% endif %}
						</div>
					{% endif %}
						<input type="hidden" id="refreshed" value="no">
					</div>
				</div>
			</div>
		</div>
		<script>
			function myFunction(state) {
				const state_value = document.getElementById("state_value")
				if (state == 'like') {
					document.getElementById("like-button").className = "bx bx-like";
				}
			}
		</script>